// ============================================================
// RECORRIDO FINAL - 47 paradas (texto fuente definitivo)
// Generado por build_data_final.py
// ============================================================

export type SectionId = 'arquitectura' | 'interior' | 'vitrales';
export type StopType = 'sala' | 'tesoro' | 'recorrido' | 'estacion';

export interface TourStop {
  id: string;
  type: StopType;
  title: string;
  subtitle: string;
  section: SectionId;
  image: string;
  audio: string;
  text: string;
  locucion: string;
}

export interface TourCategory {
  id: SectionId;
  title: string;
  description: string;
  image: string;
}

export const ALL_TOUR_STOPS: TourStop[] = [
  {
    id: 'bienvenida',
    type: 'sala',
    title: 'Bienvenida',
    subtitle: 'La historia de la promesa y el poncho del cacique que inició la gran obra.',
    section: 'arquitectura',
    image: '/bienvenida.jpg',
    audio: '/bienvenida.mp3',
    text: 'La historia de la promesa y el poncho del cacique que inició la gran obra.',
    locucion: 'Hola, ¿qué tal? Soy tu guía en esta visita a la Basílica Nuestra Señora de Luján. Nuestro punto de encuentro para comenzar es justo al frente de la Basílica, donde todo el mundo aprovecha para sacarse la foto de recuerdo. Mientras vamos hasta ahí, te cuento que esta obra se la debemos a un sacerdote francés, el Padre Jorge María Salvaire. Terminando el 00 la vida de este padre estaba en manos de unos indios, y encomendó entonces su alma a la Virgen. Si se salvaba, iba a escribir su historia y a construirle un templo monumental. En ese momento, llegó un cacique que lo conocía, y efectivamente, lo salvó. ¿Conocías la historia? Hizo lo que dijo: escribió su historia y pocos años después se comenzaba la construcción de esta gran casa, que se terminaría recién en, 0 años después,.',
  },
  {
    id: 'neogotico',
    type: 'sala',
    title: 'El Neogótico: Un Estilo que Mira al Cielo',
    subtitle: 'Los secretos de la verticalidad, la liviandad y la luz espiritual de la piedra.',
    section: 'arquitectura',
    image: '/neogotico.jpg',
    audio: '/neogotico.mp3',
    text: 'Los secretos de la verticalidad, la liviandad y la luz espiritual de la piedra.',
    locucion: 'Acá estamos, justo frente a la Basílica. Momento de sacar una foto. Lo primero que impacta es que todo parece irse para arriba. Subir y subir. Ir más alto. Entrar en el cielo. A esta forma se le llamó gótico. Tiene tres secretos: la verticalidad, porque todas las líneas son como brazos que quieren tocar el cielo; la liviandad, que nos hace sentir que el edificio flota a pesar de ser de piedra; y la luminosidad, pues, como las columnas externas aguantan todo el peso, se pueden abrir o ampliar las paredes y poner ventanas gigantes. Es una arquitectura pensada para que la luz sea la protagonista. El gótico es un estilo espiritual.',
  },
  {
    id: 'portadas',
    type: 'sala',
    title: 'Las Tres Portadas y el Abrazo a las Naciones',
    subtitle: 'Significado de las entradas dedicadas a Argentina, Uruguay y Paraguay.',
    section: 'arquitectura',
    image: '/portadas.jpg',
    audio: '/portadas.mp3',
    text: 'Significado de las entradas dedicadas a Argentina, Uruguay y Paraguay.',
    locucion: 'Si bajamos la vista a las puertas, se nota que la fachada está dividida en tres, lo que anuncia tres naves en el interior. Son las tres entradas principales con arcos apuntados, es decir, con esa forma de punta de flecha. Cada puerta representa a una nación que, en aquel entonces, ya tenía a la Virgen de Luján como su protectora. A la derecha está la de la República del Uruguay, en el centro la de Argentina y a la izquierda la del Paraguay. Este orden se mantiene en el interior con cada nave. La puerta argentina es la más ancha y está hecha de madera de roble revestida en cobre. Si miramos el tímpano hay un relieve de la Virgen rodeado de una decoración espesa de hojas de vid y parras, que las vamos a ver en muchos lugares de la Basílica. Las curvas o columnas que enmarcan cada entrada se llaman arquivoltas y acentúan esa sensación de profundidad,.',
  },
  {
    id: 'roseton',
    type: 'sala',
    title: 'Pináculos y el Gran Rosetón de Luz',
    subtitle: 'La decoración de la vid y el sello de cristal francés de diez metros.',
    section: 'arquitectura',
    image: '/roseton.jpg',
    audio: '/roseton.mp3',
    text: 'La decoración de la vid y el sello de cristal francés de diez metros.',
    locucion: 'Encima de estas entradas, coronando los arcos, aparecen los pináculos. Son esas terminaciones en punta, como agujas pequeñas, que sirven para reforzar esa idea de verticalidad. Lo interesante es que estos pináculos no están ahí solo de adorno; son el remate visual de las estructuras que realmente sostienen el edificio. Tienen una relación directa con las columnas que veremos luego. Si observamos bien sus detalles, notaremos que repiten la misma decoración de motivos naturales y actúan como las piezas que terminan de estirar la fachada hacia el cielo antes de encontrarnos, más arriba, con el gran rosetón central. El gran rosetón central es una obra imponente de 10 metros de diámetro que llegó desde Francia, y está compuesto por vitrales radiados que tamizan la luz antes de que entre al templo, 0.',
  },
  {
    id: 'apostoles',
    type: 'sala',
    title: 'Mensajeros de Piedra: Apóstoles y Evangelistas',
    subtitle: 'Los santos gigantes de la fachada que parecen caminar junto al visitante.',
    section: 'arquitectura',
    image: '/apostoles.jpg',
    audio: '/apostoles.mp3',
    text: 'Los santos gigantes de la fachada que parecen caminar junto al visitante.',
    locucion: 'Sigamos elevando la mirada porque lo que tenemos arriba es impresionante. Nos esperan estatuas de piedra, cada una de unos seis metros de alto, que representan a los Apóstoles y a los Evangelistas. Hay un detalle muy tierno en estas esculturas que no se ve a simple vista: si se fijan bien en los pies de las figuras, van a notar que sobresalen un poquito del pedestal. Dicen que se esculpieron así a propósito, para que sintamos que los santos no están ahí quietos, sino que caminan con nosotros y nos acompañan mientras entramos al templo. San Pedro tiene las llaves en la mano. ¿lo pueden ver? Él está ahí, custodiando la entrada. En total son doce apóstoles distribuidos en la fachada, y luego veremos a los evangelistas, antes de entrar,.',
  },
  {
    id: 'gargolas',
    type: 'sala',
    title: 'Gárgolas y Demonios en las Cornisas',
    subtitle: 'El misterio de los ángeles caídos que vigilan el templo desde afuera.',
    section: 'arquitectura',
    image: '/gargolas.jpg',
    audio: '/gargolas.mp3',
    text: 'El misterio de los ángeles caídos que vigilan el templo desde afuera.',
    locucion: 'Ahora, prepárense para algo un poco más misterioso. Si estiran el cuello y miran bien arriba, hacia las cornisas y los salientes más altos, van a descubrir a los "vecinos" más extraños de la Basílica: las gárgolas y esos llamativos demonios que parecen espiarnos desde las alturas. No son todos iguales; hay grifones y figuras grotescas, y un detalle que los hace realmente intrigantes es que muchos tienen alas. Según la historia, estas criaturas representan a los ángeles que fueron expulsados del Paraíso y que, al caer, quedaron atrapados en la piedra, condenados a la intemperie por toda la eternidad. Pero lo que realmente intriga es su gesto. Si los observan con detenimiento, van a notar que tienen una "actitud pensante". La tradición dice que están ahí, con el mentón apoyado en las garras, buscando una forma de entrar. Se quedan ahí, congelados en ese pensamiento eterno, tratando de descifrar cómo vulnerar el templo.',
  },
  {
    id: 'torres',
    type: 'sala',
    title: 'Torres, Campanas de Guerra y Relojes Santafesinos',
    subtitle: 'Secretos a 100 metros de altura y el carillón fundido con cañones de Milán.',
    section: 'arquitectura',
    image: '/torres.jpg',
    audio: '/torres.mp3',
    text: 'Secretos a 100 metros de altura y el carillón fundido con cañones de Milán.',
    locucion: 'Ahora sí, preparemos el cuello porque vamos a elevar la mirada bien arriba, hacia las torres simétricas de 106 metros de altura. En la torre de la izquierda se esconde el tesoro musical: un carillón de campanas de bronce. Fueron fundidas en Milán, Italia, utilizando cañones de la Segunda Guerra Mundial. Pensar que ese metal, que alguna vez fue usado para la guerra, hoy se transformó en un llamado a la paz y a la oración. Si observan bien, hay un puente que une las dos torres, es la galería a giorno, un espacio abierto que permite cruzar de un lado al otro a esa impresionante altura. Justo arriba de los campanarios aparecen los relojes. Si se fijan bien, son redondos y rompen un poco con el estilo de la Basílica. Es que fueron fabricados bien cerca, en Rosario, Santa Fe. Y sí, están siempre en hora Entremos a este templo. Entramos por el lateral izquierdo, Te espero ahí, apenas entres del lado deadentro de las rejas. frente a la Tienda, en nuestra la próxima parada.',
  },
  {
    id: 'arbotantes',
    type: 'sala',
    title: 'Las columnas de la iglesia y los cuatro evangelistas',
    subtitle: 'El perfil real del templo, los arbotantes y los símbolos de los cuatro evangelistas',
    section: 'arquitectura',
    image: '/arbotantes.jpg',
    audio: '/arbotantes.mp3',
    text: 'El perfil real del templo, los arbotantes y los símbolos de los cuatro evangelistas',
    locucion: 'Apenas entramos, está la zona de la tienda, donde llevarse genuinos objetos recordatorios. La estatua que mira afuera es el padre Salvaire, el fundador. Unos pasos más adelante, antes de las escaleras, podemos ver el perfil de la iglesia. Toda su profundidad y las estructuras que la sostienen. La estructura real del edificio. Bien arriba se puede observar como caen desde el techo los arbotantes, esos arcos externos que parecen sostener las paredes desde los costados. ¿los ven? Están todos adornados con pequeñas volutas. Gracias a ellos, el peso del techo no aplasta el edificio y permite que adentro todo sea más espacioso. Los arbotantes descargan su peso a la vez sobre las inmensas columnas laterales. Esta estructura permite grandes frentes expuestos, que serán cubiertos con los maravillosos vitrales. Volvamos la vista a la torre, al pie de la escalera. Allí están los cuatro evangelistas, los cronistas de la Biblia. Son Mateo, Marcos, Lucas y Juan. Cada uno tiene un símbolo porque representan distintas facetas de la vida de Jesús. A Mateo se lo asocia con el hombre o el niño, porque su Evangelio destaca la humanidad de Cristo; a Marcos con el león por la fuerza de Jesús; a Lucas con el buey por su carácter de sacrificio; y a Juan con el águila, porque su escritura es la más espiritual mirando a Jesús como Dios. Avancemos. Ya puedes tocar esas paredes añosas. Y al templo entero. En la proxima parada hablamos de esta piedra rosada, y algunos secretos más antes de entrar.',
  },
  {
    id: 'parada9',
    type: 'sala',
    title: 'La entrada: revestimiento de piedra y escaleras de mármol',
    subtitle: 'Piedra de Colón y mármol de Carrara antes de cruzar el umbral del silencio',
    section: 'arquitectura',
    image: '/bienvenida.jpg',
    audio: '/bienvenida.mp3',
    text: 'Piedra de Colón y mármol de Carrara antes de cruzar el umbral del silencio',
    locucion: 'Todo el revestimiento y todas las molduras están realizadas con piedra de unas canteras de Colón, Entre Ríos, que el propio Salvaire supervisó. El interior en cambio, es de ladrillos clásicos. Se instalaron dos hornos en la rivera del río, para producirlos. Te invita subir las escaleras para entrar en el El Nártex y el Umbral del Silencio Los materiales rusticos se combiann con los nobles. Si miramos al suelo, estamos pisando escalones de mármol de Carrara, traído especialmente de Italia para darle este marco de elegancia. Las puertas interiores son de roble de Eslavonia y, si se fijan en los detalles, repiten esa decoración de parras de uva y hojas de vid que ya vimos afuera. Si prestamos atención, el clima cambia totalmente apenas cruzamos la puerta. El ruido de la plaza parece quedar a kilómetros y el silencio nos empieza a envolver de a poco. Estamos en el nártex, que es como el hall de entrada del templo. Es el lugar justo para dejar las preocupaciones del mundo atrás y prepararnos para lo que viene Estás por entrar. Te dejo acá. Tomate tu tiempo. Nos vemos en nuestra próxima parada. Al entrar. En la entrada principal. Frente a la nave central. Te espero!',
  },
  {
    id: 'mapa_interior',
    type: 'sala',
    title: 'El Plan de Vuelo del Recorrido Interior',
    subtitle: 'Hoja de ruta para descubrir los tesoros respetando el espacio de oración',
    section: 'interior',
    image: '/mapa_interior.jpg',
    audio: '/recorrido_interior.mp3',
    text: 'Hoja de ruta para descubrir los tesoros respetando el espacio de oración',
    locucion: 'Ahora que estamos por empezar a caminar por dentro, vamos a organizar nuestro "plan de vuelo" para no perdernos de nada. Si se fijan en la app, tienen disponible el mapa para ir ubicándose en cada rincón de este bosque de piedra. Nuestro camino es sencillo: partimos de acá, de la puerta central, y vamos a empezar recorriendo toda el ala derecha, que es la nave dedicada al Uruguay. Vamos a ir descubriendo vitrales y altares hasta llegar al crucero. De ahí, entraremos en el Ábside —que es ese pasillo circular que rodea el altar mayor por detrás— para después emprender el regreso por el ala izquierda, la nave del Paraguay. Un pedido muy especial para nuestra caminata: como verán, este es un templo vivo, lleno de fe y de personas que vienen a practicarla en silencio. Por eso, no nos vamos a meter en la nave central, que es el espacio sagrado de oración, ni vamos a caminar directamente frente al altar o subir al Camarín de la Virgen mientras recorremos las naves. Vamos a ir por los laterales, como observadores silenciosos, disfrutando de los tesoros de la Basílica sin romper ese clima tan especial que se siente en el aire. ¿Listos? Si se dan vuelta hacia la puerta por la que entramos, empezamos con la enseñanza de los vitrales,',
  },
  {
    id: 'navecentral',
    type: 'sala',
    title: 'La Nave Central: Un Bosque de Piedra',
    subtitle: 'La inmensidad de la planta en cruz latina y el camino espiritual al altar 0.',
    section: 'interior',
    image: '/navecentral.jpg',
    audio: '/navecentral.mp3',
    text: 'La inmensidad de la planta en cruz latina y el camino espiritual al altar 0.',
    locucion: 'Si miramos hacia adelante, el espacio impresiona por su escala y es difícil no quedarse un segundo sin palabras. Son 00 metros de largo hasta el fondo, una distancia que representa nuestro "largo caminar" para llegar al altar. Si pudiéramos ver este edificio desde el cielo, notaríamos que toda la planta tiene forma de cruz latina, dibujando la crucifixión de Jesús directamente sobre el suelo de Luján. Las columnas que dividen las naves se llaman pilares compuestos y son como los músculos que sostienen todo este peso. Si seguimos sus líneas hacia arriba, vemos que se ramifican en el techo formando bóvedas de crucería que parecen un bosque de piedra protegiéndonos.',
  },
  {
    id: 'vitrales',
    type: 'sala',
    title: 'La Tabla de los Pobres: El Arte del Vitral',
    subtitle: 'Cómo leer las historias sagradas a través del cristal, el color y el plomo.',
    section: 'interior',
    image: '/vitrales.jpg',
    audio: '/vitrales.mp3',
    text: 'Cómo leer las historias sagradas a través del cristal, el color y el plomo.',
    locucion: 'Estamos acá parados, justo en la entrada central, y es el único lugar donde tenemos los vitrales bien cerca, casi al alcance de la mano. Antes les decían "la tabla de los pobres" porque, en una época donde mucha gente no sabía leer ni escribir, las historias de la fe se aprendían mirando estos dibujos. Son como un libro de cristal que se lee de arriba hacia abajo. Los colores que ven, el rojo, el verde, el dorado y el azul, son clásicos de la firma Dagrand de Burdeos, en Francia. Pucha, pensar que el diseño original lo hizo el propio padre Salvaire, que dibujó cada escena antes de mandarlas a fabricar a Europa. vamos ahora a comenzar el recorrido de las neves, y comenzamos por la derecha, por al nave del uruguay en su primer parada: El nacimiento y bautismo de JEsús.',
  },
  {
    id: 'bautismo',
    type: 'sala',
    title: 'El Bautismo y el Círculo de la Vida',
    subtitle: 'El vitral del río Jordán bajo el simbolismo eterno del Alfa y el Omega.',
    section: 'interior',
    image: '/bautismo.jpg',
    audio: '/bautismo.mp3',
    text: 'El vitral del río Jordán bajo el simbolismo eterno del Alfa y el Omega.',
    locucion: 'En este primer vitral a nuestra derecha vemos una escena que todos conocemos: el bautismo de Jesús en el río Jordán. Si nos fijamos en el circulito de cristal que está bien arriba, vamos a ver representada a la Santísima Trinidad rodeada por las letras Alfa y Omega. Es un símbolo hermoso que nos recuerda que Cristo es el principio y el fin de todas las cosas. Justo abajo está el bautisterio de roble, que hace juego con el vitral. Hoy los bautismos se suelen hacer en el patio de la basílica porque son muy masivos, pero este rincón mantiene el significado de nuestro primer paso en la fe.',
  },
  {
    id: 'reyes',
    type: 'sala',
    title: 'Reyes, Emperadores y el Pesebre de Roma',
    subtitle: 'Historias de Constantino, Carlos Magno y el nacimiento premiado en Italia.',
    section: 'interior',
    image: '/reyes.jpg',
    audio: '/reyes.mp3',
    text: 'Historias de Constantino, Carlos Magno y el nacimiento premiado en Italia.',
    locucion: 'Si seguimos elevando la vista, aparecen el emperador Constantino con su cruz luminosa y Carlos Magno con la corona. El diseño que eligió Salvaire es muy práctico: arriba tenemos al personaje bien grande y abajo el dibujo nos cuenta un poquito de su historia. Pero miren ahora este mueble de madera que tenemos abajo: es el Pesebre de Nazaret. Este nacimiento es famoso porque participó en un concurso en Roma y sacó el tercer premio, nada menos. Cuando lo donaron a la basílica, tuvieron que hacer una adaptación porque era tan grande que no entraba completo. Fíjense en los detalles de las casitas y las ovejitas, es una maravilla cómo lograron recrear ese ambiente tan especial.',
  },
  {
    id: 'predicadores',
    type: 'sala',
    title: 'Predicadores en América y los Pieles Rojas',
    subtitle: 'La misión de San Francisco Solano y el detalle de los niños indígenas.',
    section: 'interior',
    image: '/predicadores.jpg',
    audio: '/predicadores.mp3',
    text: 'La misión de San Francisco Solano y el detalle de los niños indígenas.',
    locucion: 'Aquí la historia se pone más cerca nuestro, con San Toribio y San Francisco Solano predicando en tierras americanas. Si observamos con cuidado al indio sentado a la derecha en el vitral de Francisco, hay un detalle que siempre me hace sonreír. ¡Es un piel roja! Nosotros por acá no tenemos piel roja, como se nombraba antes a los pueblos originarios de norteamérica, pero se ve que el artesano en Francia, que nunca había visto américa de cerca, se los imaginó así.',
  },
  {
    id: 'confesionarios',
    type: 'sala',
    title: 'Los Confesionarios y el Vía Crucis',
    subtitle: 'El alivio del alma y el camino de la cruz presentes en los muros laterales,',
    section: 'interior',
    image: '/confesionarios.jpg',
    audio: '/confesionarios.mp3',
    text: 'El alivio del alma y el camino de la cruz presentes en los muros laterales,',
    locucion: 'Caminando por esta nave derecha, si prestamos atención a los muros laterales que separan las capillas, van a ver aparecer los confesionarios de madera tallada. Es lindo imaginar lo que soñaron los constructores: ellos decían que si la Basílica es el cuerpo de Cristo, el Altar Mayor es su cabeza y el Ábside —que rodea el altar— es su corona de espinas. De esa corona destila la sangre redentora que fluye hacia estos costados para bañar los confesionarios y purificar los pecados de los fieles. Fíjense también en las paredes laterales de los altares: ahí mismo empieza el Vía Crucis, contado en imágenes de cerámica fabricadas por la casa Dagrand en Francia. A veces uno piensa que los confesionarios deberían estar en un rincón escondido, pero acá nos salen al encuentro en plena nave, recordándonos que el perdón y el camino de la cruz están siempre a mano para quien quiera empezar de nuevo.',
  },
  {
    id: 'alturas_nave',
    type: 'sala',
    title: 'Las Alturas: Doctores, Escudos y el Triforio',
    subtitle: 'Sabios de la fe y el país entero presente en lo más alto de la nave 0,.',
    section: 'interior',
    image: '/alturas_nave.jpg',
    audio: '/alturas_nave.mp3',
    text: 'Sabios de la fe y el país entero presente en lo más alto de la nave 0,.',
    locucion: 'Antes de seguir caminando, los invito a que se arrimen un poquito al borde de las columnas para asomarse a la nave central y elevar la mirada bien arriba. Pucha, miren lo que son esas lámparas, a las que acá les decimos arañas. La primera, bien gótica, representa al gobierno de Irlanda; pero fíjense en la otra, la que trajeron del Teatro Ópera de Buenos Aires: es una maravilla que tiene cerca de 00 tulipas de cristal; imaginen lo que es eso encendido. Ahora, si miran justo por encima de los arcos, van a ver una galería estrecha de tres ventanas: es el triforio. Sus tres aberturas representan a la Santísima Trinidad: Padre, Hijo y Espíritu Santo. Debajo de esa galería aparecen unas figuras imponentes que a veces confundimos con los apóstoles, pero no; son los Doctores de la Iglesia, los grandes sabios —sacerdotes, obispos y papas— que con sus escritos iluminaron la fe. Y si miran todavía más arriba, donde el techo empieza a curvarse, van a descubrir los escudos de todas nuestras provincias argentinas, recordándonos que el país entero está presente y bajo este mismo techo de luz,.',
  },
  {
    id: 'martires',
    type: 'sala',
    title: 'San Pascual Bailón y los Mártires Decapitados',
    subtitle: 'El santo que adoraba bailando y el sacrificio final de Bernabé y Matías 0.',
    section: 'interior',
    image: '/martires.jpg',
    audio: '/martires.mp3',
    text: 'El santo que adoraba bailando y el sacrificio final de Bernabé y Matías 0.',
    locucion: 'San Pascual Bailón es un personaje que me encanta porque adoraba al Santísimo de una manera muy particular: lo hacía bailando. De ahí viene su nombre y ese gesto de alegría que se ve en el cristal, porque para él la fe era una fiesta. Pero al lado, la cosa se pone un poco más seria y dramática con San Bernabé y San Matías. El vitral no nos oculta nada y muestra el momento de su entrega final, cuando les cortan la cabeza por no renunciar a lo que creían. Es un contraste fuerte entre la alegría del baile y la dureza del martirio, dos formas muy distintas de dar la vida por una idea.',
  },
  {
    id: 'sanantonio',
    type: 'sala',
    title: 'Altar de San Antonio: El Regalo Irlandés',
    subtitle: 'Mármol puro donado por Margarita Morgan y el secreto sagrado del Ara.',
    section: 'interior',
    image: '/sanantonio.jpg',
    audio: '/sanantonio.mp3',
    text: 'Mármol puro donado por Margarita Morgan y el secreto sagrado del Ara.',
    locucion: 'Este es el primero de los altares laterales que tiene la basílica y es imponente porque es todo de mármol de Carrara. Lo donó Margarita Morgan, una irlandesa que fue una gran benefactora y que quiso dejar su huella en este templo. Si nos fijamos en la mesa del altar, hay un pequeño recuadro que se llama Ara. Adentro de ese espacio se guarda una reliquia diminuta de un mártir o un santo, que es lo que "habilita" el altar para poder dar misa. Sin esa reliquia, la consagración no se podría hacer; es como el motor espiritual de toda la estructura de mármol.',
  },
  {
    id: 'sanroque',
    type: 'sala',
    title: 'San Roque y el Pan del Desierto',
    subtitle: 'La lealtad del perro que salvó al santo enfermo en su soledad.',
    section: 'interior',
    image: '/sanroque.jpg',
    audio: '/sanroque.mp3',
    text: 'La lealtad del perro que salvó al santo enfermo en su soledad.',
    locucion: 'Para terminar este primer tramo de la caminata, busquemos la imagen de San Roque. Siempre lo vamos a reconocer porque tiene un perro al lado, y esa es una historia de lealtad que me conmueve. La tradición cuenta que cuando Roque estaba enfermo y abandonado en el desierto, nadie se le acercaba por miedo al contagio. Pero este perro le robaba un pedazo de pan a su dueño todos los días para llevárselo y que no muriera de hambre. Gracias a ese animalito, el santo pudo sobrevivir a la soledad y a la enfermedad. Por eso el perro aparece siempre con el pan en la boca, recordándonos que a veces la ayuda viene de donde menos la esperamos.',
  },
  {
    id: 'crucero',
    type: 'sala',
    title: 'El Crucero: Los Brazos de la Basílica',
    subtitle: 'El ensanche del templo que representa simbólicamente el pecho de Cristo',
    section: 'interior',
    image: '/crucero.jpg',
    audio: '/crucero.mp3',
    text: 'El ensanche del templo que representa simbólicamente el pecho de Cristo',
    locucion: 'Estamos parados en el crucero, que vendría a ser como el pecho de la Basílica si miramos el dibujo del suelo. Si recordamos que el plano del templo tiene forma de cruz latina, acá es donde los dos brazos se cruzan y el espacio se abre hasta alcanzar los 0 metros de ancho. La sensación de amplitud en este punto es increíble y nos permite ver la magnitud real de lo que se construyó hace más de cien años. Es el corazón geográfico del santuario, el punto de encuentro natural de todos los que venimos caminando desde distintas naves. Se siente como un respiro profundo en medio del recorrido, un lugar ideal para dimensionar la grandeza de este estilo neogótico.',
  },
  {
    id: 'altar_mayor',
    type: 'sala',
    title: 'El Altar Mayor: Cabeza y Corazón de Cristo',
    subtitle: 'El sacrificio eucarístico bajo el trono de gloria de la Virgen María 0.',
    section: 'interior',
    image: '/altar_mayor.jpg',
    audio: '/altar_mayor.mp3',
    text: 'El sacrificio eucarístico bajo el trono de gloria de la Virgen María 0.',
    locucion: 'Si nos detenemos un momento antes de seguir por los vitrales laterales y miramos hacia nuestra izquierda, nos vamos a encontrar con el Altar Mayor. Es una obra imponente hecha totalmente de mármol de Carrara traído de Italia, y está rodeado por estatuas de santos que parecen custodiar el lugar. Pero lo más especial es lo que representa para la fe: el Cuerpo de Cristo. La mesa donde se celebra la misa es el Corazón, el sagrario que vemos detrás es la Cabeza y los brazos del crucero que se abren a los lados representan sus Brazos. También se lo conoce como la Corona de Cristo. Dicen que, en el momento de la consagración, la misericordia emana desde este centro y fluye hacia los confesionarios de las naves, como si fuera sangre purificadora que nos limpia de los pecados. Pucha, es un detalle que te hace ver a la Basílica no como un edificio de piedra, sino como un organismo que late y respira junto con nosotros',
  },
  {
    id: 'medalla',
    type: 'sala',
    title: 'La Medalla Milagrosa y el Sepulcro de Salvaire',
    subtitle: 'El auxilio de la Virgen y el lugar de descanso del gran fundador.',
    section: 'interior',
    image: '/medalla.jpg',
    audio: '/medalla.mp3',
    text: 'El auxilio de la Virgen y el lugar de descanso del gran fundador.',
    locucion: 'Este vitral es uno de los más cargados de significado porque nos cuenta varias cosas a la vez. En una parte vemos a la Virgen auxiliando a las almas del purgatorio, que es una imagen muy fuerte de consuelo y esperanza para los que ya no están. También aparece el momento en que se le aparece a Catalina Labouré para pedirle que acuñe la famosa Medalla Milagrosa. Llegamos a un rincón de mucha paz, que es el sepulcro de los fundadores de la Basílica. Acá descansan los restos del padre Salvaire y de los que siguieron su "locura" de piedra, como Monseñor Dabani y el padre George. Salvaire murió en, sin ver la obra terminada, pero sus sucesores se encargaron de que cada ladrillo se pusiera en su lugar siguiendo su visión,.',
  },
  {
    id: 'angel',
    type: 'sala',
    title: 'El Ángel Orante de la Percepción',
    subtitle: 'El arcángel de tres alas que ayuda a agudizar los sentidos espirituales.',
    section: 'interior',
    image: '/angel.jpg',
    audio: '/angel.mp3',
    text: 'El arcángel de tres alas que ayuda a agudizar los sentidos espirituales.',
    locucion: 'Si nos detenemos frente a esta imagen, es probable que notemos algo extraño en sus alas. Este arcángel tiene tres, aunque la tercera parece más bien una capita que lo envuelve. En la tradición del santuario, se lo conoce como el ángel de la percepción y hay mucha gente que se acerca a tocar esa tercera ala con la esperanza de agudizar sus sentidos espirituales o encontrar claridad en momentos de duda. Es una imagen que nos invita a pensar que hay realidades que no se ven a simple vista y que hace falta una sensibilidad especial para captar lo sagrado en lo cotidiano. Otro detalle, las piedras escritas con nombres. ¿que significan?',
  },
  {
    id: 'piedras',
    type: 'sala',
    title: 'Las Piedras Escritas y las Intenciones Ocultas',
    subtitle: 'Muros que guardan en su interior los mensajes y promesas de los fieles.',
    section: 'interior',
    image: '/piedras.jpg',
    audio: '/piedras.mp3',
    text: 'Muros que guardan en su interior los mensajes y promesas de los fieles.',
    locucion: 'Estas paredes que nos rodean no son solo piedra y cemento, tienen un alma propia que late en cada bloque. Se las conoce como las "piedras escritas" porque son bloques huecos que se vendieron para juntar los fondos necesarios para terminar esta obra inmensa. Adentro de cada una, la gente dejaba frasquitos de vidrio con sus intenciones, sus promesas o simplemente los nombres de sus seres queridos. Es impresionante pensar que estamos rodeados por miles de oraciones secretas que están ahí, metidas en la estructura misma de la Basílica. entremos ahora en el abside, que rodea al altar por detras,',
  },
  {
    id: 'sentido_abside',
    type: 'sala',
    title: 'El Sentido del Ábside: La Corona Purificadora',
    subtitle: 'La corona de espinas de donde destila la sangre que baña los confesionarios',
    section: 'interior',
    image: '/sentido_abside.jpg',
    audio: '/sentido_abside.mp3',
    text: 'La corona de espinas de donde destila la sangre que baña los confesionarios',
    locucion: 'Si nos detenemos en el eje de la planta, justo antes de entrar al pasillo circular, estamos entrando al Ábside. Teológicamente, como dijimos antes, si la Basílica es el cuerpo de Cristo, este sector representa su Corona de Espinas. Los constructores soñaron que, desde este lugar sagrado, la sangre redentora de Jesús destila y fluye hacia las naves laterales para bañar los confesionarios. Es una imagen fuerte: la misericordia nace aquí, en la "cabeza" del templo, y se derrama hacia afuera para perdonar a los fieles. Comencemos por el primer altar a la derecha, de San vicente de paul.',
  },
  {
    id: 'sanvicente',
    type: 'sala',
    title: 'San Vicente de Paul y Santa Luisa de Marillac',
    subtitle: 'La caridad vicentina y la base de mármol con mosaicos venecianos.',
    section: 'interior',
    image: '/sanvicente.jpg',
    audio: '/sanvicente.mp3',
    text: 'La caridad vicentina y la base de mármol con mosaicos venecianos.',
    locucion: 'Este altar es otra joya que le debemos a la generosidad de la familia Morgan, que tanto ayudó en la construcción. Está dedicado a San Vicente de Paul, ese gran ejemplo de caridad y entrega. Si nos acercamos un poquito a la base, vamos a notar unos mosaicos venecianos preciosos que le dan un toque de color y brillo diferente al mármol de Carrara. Es un altar que nos habla del servicio a los demás y de cómo la fe echó raíces profundas y hermosas en estas tierras americanas. Seguimos por el altar a san jeremías nuestra proxima parada.',
  },
  {
    id: 'santarosa',
    type: 'sala',
    title: 'Santa Rosa de Lima: Mosaicos Venecianos',
    subtitle: 'Homenaje a la primera santa de América con detalles de brillo italiano.',
    section: 'interior',
    image: '/santarosa.jpg',
    audio: '/santarosa.mp3',
    text: 'Homenaje a la primera santa de América con detalles de brillo italiano.',
    locucion: '(Integrada en la locución anterior de San Vicente de Paul, destacando a la primera santa de nuestro continente y los mosaicos venecianos de la base)',
  },
  {
    id: 'sanjose',
    type: 'sala',
    title: 'San José y el Monstruo del Mar',
    subtitle: 'La protección del Arcángel Rafael durante el viaje del joven Tobías.',
    section: 'interior',
    image: '/sanjose.jpg',
    audio: '/sanjose.mp3',
    text: 'La protección del Arcángel Rafael durante el viaje del joven Tobías.',
    locucion: 'Llegamos al altar de San José, que fue terminado con un estilo un poco más sencillo que los anteriores. El vitral de acá nos cuenta una historia que parece sacada de un libro de aventuras: el arcángel Rafael protegiendo al joven Tobías del ataque de un monstruo marino. Es una imagen muy dinámica que nos recuerda que siempre tenemos una protección superior cuando enfrentamos nuestros miedos o las dificultades del viaje. San José, como custodio de la Sagrada Familia, acompaña este mensaje de cuidado y guía en nuestro propio caminar diario',
  },
  {
    id: 'sanluis',
    type: 'sala',
    title: 'San Luis Gonzaga: El Altar de Latón',
    subtitle: 'Un rincón de imitación colonial con pinturas al óleo sobre metal.',
    section: 'interior',
    image: '/sanluis.jpg',
    audio: '/sanluis.mp3',
    text: 'Un rincón de imitación colonial con pinturas al óleo sobre metal.',
    locucion: 'Si observamos este rincón, vamos a notar que el estilo cambia de repente y nos traslada a algo más colonial. Es el altar de San Luis Gonzaga y lo que lo hace tan especial es que no es de mármol como los demás, sino que está hecho de latón. Este material le da un brillo y una textura diferente, contándonos la historia de este joven jesuita que dio su vida cuidando a los enfermos en medio de una peste en Roma. Es un recordatorio de que la fe también se construye con materiales sencillos y que la entrega no conoce de edades.',
  },
  {
    id: 'sanjeremias',
    type: 'sala',
    title: 'San Jeremías y el Altar del Silencio',
    subtitle: 'Donación de Margarita Morgan dedicada a los padres del desierto, 0.',
    section: 'interior',
    image: '/sanjeremias.jpg',
    audio: '/sanjeremias.mp3',
    text: 'Donación de Margarita Morgan dedicada a los padres del desierto, 0.',
    locucion: 'Este altar es otro regalo de la generosa Margarita Morgan para encomendar a su hijo Jeremías. Aquí vemos estatuas de santos irlandeses como San Lorenzo O\'Toole, pero presten atención al vitral central: allí está San Bruno, el fundador de la orden de los Cartujos. Los cartujos son famosos por sus estrictos votos de silencio. En un mundo con tanto ruido, este rincón nos invita a buscar un momento de paz profunda y a recordar que Dios también habla cuando nos callamos. Llegamos a la Cámara intima de la virgen en el centro vertical del templo. De un lado veremos la entrada a la sacristía y del otro, a la cámara intima de la virgen.',
  },
  {
    id: 'camarin_sacristia',
    type: 'sala',
    title: 'Cámara Íntima de la Virgen',
    subtitle: 'Lugar de oración y preparación donde reside la imagen original de 1600.',
    section: 'interior',
    image: '/camarin_sacristia.jpg',
    audio: '/camarin_sacristia.mp3',
    text: 'Lugar de oración y preparación donde reside la imagen original de 1600.',
    locucion: 'Estamos llegando al corazón más reservado del santuario: el Camarín de la Virgen. Aquí es donde late la vida consagrada, conectando la Sacristía Principal —donde los sacerdotes se preparan para el culto— con la cámara íntima de María. Es un espacio de oración profunda donde la imagen original bendiga tanto a los fieles en la nave como a quienes suben hasta este umbral de gloria. Antes de entrar, donde por respeto, no usaremos esta guia, te comento. Este es el lugar donde los fieles nos sentimos más cerca de nuestra Madre. Fíjense que a los pies de María hay dos ángeles dorados que sostienen incensarios, que son el símbolo de nuestra oración que sube al cielo. El retablo que la rodea es una obra de arte con dos historias talladas: a la derecha, la agonía de Jesús en Getsemaní, y a la izquierda, la cena de Emaús. En el centro del altar van a ver otro relieve que muestra la muerte de San José en brazos de Jesús y María. Los invita entrar en silencio y tomarse su tiempo. LOs espero acá tod el tiempo que haga falta.',
  },
  {
    id: 'alturas_izq',
    type: 'sala',
    title: 'Alturas de la Izquierda: Santa Cecilia y la Música',
    subtitle: 'La patrona de los músicos observando desde lo alto del ábside,.',
    section: 'interior',
    image: '/alturas_izq.jpg',
    audio: '/alturas_izq.mp3',
    text: 'La patrona de los músicos observando desde lo alto del ábside,.',
    locucion: 'Si elevan la vista hacia los vitrales superiores de este lado, van a encontrar a Santa Cecilia. Se la reconoce porque está tocando el órgano acompañada por ángeles. Es la patrona de los músicos y parece estar ahí custodiando la armonía de este bosque de piedra. Desde esta altura, también podemos apreciar el Triforio del lado izquierdo, esa galería de tres arcos que vuelve a recordarnos la presencia de la Santísima Trinidad en cada rincón del templo.',
  },
  {
    id: 'jesuitas',
    type: 'sala',
    title: 'San Ignacio y los Jesuitas: El Camino de Javier',
    subtitle: 'La presencia de Loyola y la misión evangelizadora en tierras lejanas,.',
    section: 'interior',
    image: '/jesuitas.jpg',
    audio: '/jesuitas.mp3',
    text: 'La presencia de Loyola y la misión evangelizadora en tierras lejanas,.',
    locucion: 'Este altar de ónix de San Luis y bronce nos conecta con la Compañía de Jesús. Vemos a San Ignacio de Loyola y también a San Francisco Javier, el gran misionero de Oriente. Es un homenaje a los jesuitas que tanto trabajaron en nuestra América. Los vitrales superiores nos muestran a otros gigantes de la fe como San Juan de la Cruz y San Juan de Dios, recordándonos que el camino a la santidad tiene muchas formas, desde la misión hasta la poesía mística.',
  },
  {
    id: 'sancarlos',
    type: 'sala',
    title: 'San Carlos Borromeo: Mosaicos Dorados',
    subtitle: 'Un altar destacado por su brillo y la devoción al santo cardenal.',
    section: 'interior',
    image: '/sancarlos.jpg',
    audio: '/sancarlos.mp3',
    text: 'Un altar destacado por su brillo y la devoción al santo cardenal.',
    locucion: 'Miren lo que es este altar de San Carlos Borromeo. Lo primero que nos llama la atención es ese brillo tan especial de sus mosaicos bizantinos. Tienen un secreto técnico increíble: fueron hechos con incrustaciones que permiten lavarlos a fondo sin que el dorado pierda ni un poquito de su luz original. Pero ahora, los invito a mirar el vitral de la izquierda, que nos cuenta la historia de Santa Inés de abajo hacia arriba. Empieza cuando ella rechaza casarse con el hijo del prefecto de Roma para consagrarse a Dios; por eso la amenazan con la cárcel y con quitarle su pudor. Pero fíjense en el centro: un ángel baja del cielo para vestirla y cuidarla. En la escena de la derecha, el muchacho intenta acercarse de nuevo y cae muerto, pero Inés reza por él y lo resucita. Al final, aunque intentan quemarla y las llamas no la tocan, termina siendo degollada. Por eso se dice que alcanzó la "doble corona": la de virgen y la de mártir.',
  },
  {
    id: 'rosario_pompeya',
    type: 'sala',
    title: 'El Santo Rosario y el Altar de Nuestra Señora de Pompeya',
    subtitle: 'Homenaje a la familia de Jesús y la entrega del Rosario.',
    section: 'interior',
    image: '/rosario_pompeya.jpg',
    audio: '/rosario_pompeya.mp3',
    text: 'Homenaje a la familia de Jesús y la entrega del Rosario.',
    locucion: 'En esta tercera capilla del ábside nos recibe Nuestra Señora del Rosario de Pompeya. La imagen es muy clara: la Virgen y el Niño le están entregando el rosario a Santo Domingo de Guzmán y a Santa Catalina. Además, fíjense en las ventanas laterales; allí están representados los misterios del Santo Rosario. Es como tener todo el camino de la vida de Jesús y María contado en estas pequeñas escenas de cristal que rodean a la Virgen coronada.',
  },
  {
    id: 'sanpatricio',
    type: 'sala',
    title: 'San Patricio: De Pastor a Guerrero',
    subtitle: 'La vida del patrono de Irlanda leída paso a paso de abajo hacia arriba.',
    section: 'interior',
    image: '/sanpatricio.jpg',
    audio: '/sanpatricio.mp3',
    text: 'La vida del patrono de Irlanda leída paso a paso de abajo hacia arriba.',
    locucion: 'Este altar es otra muestra del cariño que la comunidad irlandesa le tiene a esta Basílica y se lee de abajo hacia arriba para seguir el crecimiento de Patricio. Primero lo vemos como un humilde pastor que fue llevado como esclavo, pero que después de escapar volvió a su tierra para predicar con una fuerza de guerrero espiritual. La historia de Irlanda está grabada en estos cristales, mostrando cómo él usaba el trébol para explicar algo tan difícil como la Trinidad',
  },
  {
    id: 'sagradocorazon',
    type: 'sala',
    title: 'El Sagrado Corazón de Jesús (Crucero Oriental)',
    subtitle: 'El amor infinito y el sacrificio del sepulcro custodiados por el carisma franciscano.',
    section: 'interior',
    image: '/sagradocorazon.jpg',
    audio: '/sagradocorazon.mp3',
    text: 'El amor infinito y el sacrificio del sepulcro custodiados por el carisma franciscano.',
    locucion: 'Nos encontramos ahora en el brazo izquierdo del crucero, un sector del templo donde la arquitectura y el arte se unen para honrar una de las devociones más profundas: el Sagrado Corazón de Jesús. Si elevan la vista hacia la parte superior de todas las ventanas de este tramo, notarán un detalle de identidad único: todas llevan en su cruz o cuadrilóbulo la representación del Sagrado Corazón, pues todo este crucero está consagrado a su amor. El altar que tenemos frente a nosotros es una obra que busca la simetría perfecta con el Santuario, ya que reproduce fielmente la estructura del Altar de la Medalla Milagrosa situado justo enfrente, en la nave de Uruguay. En su centro, la imagen del Sagrado Corazón de Jesús irradia su misericordia, mientras es custodiado a ambos lados por las estatuas de San Francisco de Asís y Santa Clara, figuras fundamentales del carisma franciscano que aquí actúan como guardianes de este misterio. Si bajamos la mirada hacia el retablo, en la mesa del altar, descubrimos un gran bajo relieve de una calidad excepcional que representa el momento de mayor entrega: cuando el cuerpo de Jesús es llevado al sepulcro. Es un contraste conmovedor entre el corazón vivo que arde de amor en la parte superior y el sacrificio final del cuerpo depositado en la piedra antes de la Resurrección. Finalmente, en lo alto, los vitrales tamizan la luz para narrar las apariciones de Jesús revelando su Sagrado Corazón, destacando especialmente los encuentros místicos con Santa Margarita María Alacoque. Salimos del crucero y nos encaminamos de regreso por la nave izquierda.',
  },
  {
    id: 'nave_paraguay',
    type: 'sala',
    title: 'La Nave del Paraguay: El Camino de Regreso y la Pasión',
    subtitle: 'Recorrido por el ala izquierda de la Basílica, desde la familia de Jesús hasta el sacrificio en la Cruz.',
    section: 'interior',
    image: '/nave_paraguay.jpg',
    audio: '/nave_paraguay.mp3',
    text: 'Recorrido por el ala izquierda de la Basílica, desde la familia de Jesús hasta el sacrificio en la Cruz.',
    locucion: 'Ahora iniciamos el tramo final de nuestro viaje por la Nave del Paraguay, el ala izquierda del templo que completa el abrazo a las naciones que vimos en la fachada. Este camino de regreso comienza en el Altar de Santa Ana, donde la familia terrenal de Jesús nos recibe con las imágenes de San Joaquín, Santa Rita y el popular San Expedito. A diferencia de la nave central, aquí nos vamos a detener en objetos preciosos que tenemos al alcance de nuestras manos, como los confesionarios de roble tallados con motivos neogóticos y lasesculturas de jesús, la virgen y el negro manuel.. Mientras avanzamos, pasaremos por las capillas dedicadas a grandes testigos: veremos los vitrales de San Esteban y San Lorenzo, el primer mártir y el diácono de los pobres; seguiremos por el altar de San Cayetano y el de San Martín de Tours, el soldado que compartió su capa con Cristo mendigo. Casi llegando al final, cruzaremos bajo el gran rosetón de la puerta lateral que lleva el Monograma de María, para terminar nuestro camino en la Capilla del Misterio de la Pasión. comencemos',
  },
  {
    id: 'santaana',
    type: 'sala',
    title: 'El Santo Rosario y el Altar de Santa Ana',
    subtitle: 'Homenaje a la familia de Jesús, San Joaquín y la Virgen del Rosario,.',
    section: 'interior',
    image: '/santaana.jpg',
    audio: '/santaana.mp3',
    text: 'Homenaje a la familia de Jesús, San Joaquín y la Virgen del Rosario,.',
    locucion: 'Entrando ya en el regreso por la nave izquierda, nos recibe el altar dedicado a la familia terrenal de Jesús. Aquí están Santa Ana y San Joaquín, los abuelos del Señor. Pero fíjense que también aparece la Virgen del Rosario de Pompeya entregando las cuentas de oración a Santo Domingo y Santa Catalina. Es un rincón muy familiar, que nos habla de las raíces y de esa devoción tan nuestra que es el rezo del Rosario como una cadena que nos une al cielo.',
  },
  {
    id: 'donbosco',
    type: 'sala',
    title: 'Don Bosco y Ceferino Namuncurá',
    subtitle: 'La devoción salesiana unida a la historia del origen de la Basílica,.',
    section: 'interior',
    image: '/donbosco.jpg',
    audio: '/donbosco.mp3',
    text: 'La devoción salesiana unida a la historia del origen de la Basílica,.',
    locucion: 'No podíamos pasar por Luján sin saludar a la familia salesiana. Aquí la imagen de Don Bosco se encuentra con la de Ceferino Namuncurá, el "lirio de la Patagonia". Hay un hilo invisible que une a Ceferino con este lugar: él era hijo del cacique Namuncurá, de la misma estirpe de aquel que le tiró el poncho a Salvaire para salvarle la vida y permitir que esta Basílica fuera una realidad. Es un encuentro entre la educación, la juventud y nuestras raíces indígenas.',
  },
  {
    id: 'burro',
    type: 'sala',
    title: 'San Antonio y el Burro Arrodillado',
    subtitle: 'La prueba de fe ante la Eucaristía que asombró a los incrédulos.',
    section: 'interior',
    image: '/burro.jpg',
    audio: '/burro.mp3',
    text: 'La prueba de fe ante la Eucaristía que asombró a los incrédulos.',
    locucion: 'Este es un vitral que siempre saca una sonrisa por lo inusual de la escena que cuenta. Se dice que San Antonio quería demostrarle la verdad de la Eucaristía a alguien que no creía, y para hacerlo, dejó a un burro sin comer durante varios días. Cuando le pusieron comida adelante y al mismo tiempo Antonio le mostró la hostia consagrada, el animal prefirió arrodillarse ante Jesús que ir a comer. Es una forma muy sencilla y pedagógica de decir que hasta la creación entera reconoce lo sagrado.',
  },
  {
    id: 'martin',
    type: 'sala',
    title: 'San Esteban y el Soldado de la Capa',
    subtitle: 'El martirio de las piedras y el encuentro de San Martín con el mendigo.',
    section: 'interior',
    image: '/martin.jpg',
    audio: '/martin.mp3',
    text: 'El martirio de las piedras y el encuentro de San Martín con el mendigo.',
    locucion: 'En esta zona vemos el contraste entre el primer mártir de la Iglesia, San Esteban, que murió bajo una lluvia de piedras por defender su fe, y la ternura de San Martín de Tours. Martín era un soldado romano que, al ver a un mendigo muerto de frío, no dudó en cortar su capa a la mitad para compartirla con él. Lo más emocionante de esa historia es que después se dio cuenta de que ese mendigo era el mismísimo Jesús.',
  },
  {
    id: 'negro_manuel',
    type: 'sala',
    title: 'El Negro Manuel y la Historia del Milagro',
    subtitle: 'El fiel custodio y el relato de cómo la Virgen decidió quedarse en Luján,.',
    section: 'interior',
    image: '/negro_manuel.jpg',
    audio: '/negro_manuel.mp3',
    text: 'El fiel custodio y el relato de cómo la Virgen decidió quedarse en Luján,.',
    locucion: 'Llegando ya casi a la salida por la nave del Paraguay, nos encontramos con la imagen de alguien fundamental: el Negro Manuel. Él era el esclavo que venía en la carreta en 1600 y fue quien propuso "trocar los cajones" para descubrir que la Virgen se quería quedar aquí. Manuel se consideró siempre "hijo de la Virgen" y dedicó toda su vida a cuidarla como su primer sacristán. Sin su fidelidad y sus relatos a los viajeros, quizás la devoción a nuestra patrona no habría llegado a ser lo que es hoy.',
  },
  {
    id: 'pasion',
    type: 'sala',
    title: 'El Misterio de la Pasión de Cristo Redentor',
    subtitle: 'El sacrificio final en la cruz y el legado de la comunidad redentorista en un espacio sin altar.',
    section: 'interior',
    image: '/pasion.jpg',
    audio: '/pasion.mp3',
    text: 'El sacrificio final en la cruz y el legado de la comunidad redentorista en un espacio sin altar.',
    locucion: 'Hemos llegado a la séptima capilla de esta nave del Paraguay, la última que visitaremos antes de encaminarnos hacia la salida. Este es un rincón que se distingue de todos los anteriores porque, si se fijan bien, no posee altar; está consagrada íntegramente al Misterio de la Pasión de Cristo Redentor. En el centro nos recibe una escultura imponente de Cristo Crucificado, acompañado por las figuras de San Juan y la Virgen Dolorosa, capturando el momento exacto del sacrificio supremo. Si elevan la mirada hacia la ventana, podrán descubrir la representación de la comunidad redentorista y su devoción a Nuestra Señora del Perpetuo Socorro, quienes custodian este espacio de profunda entrega. Es un lugar para el silencio, donde recordamos que Cristo funda su Iglesia precisamente al morir en la cruz por nosotros. Como dice la tradición de este santuario, después de haber caminado entre tantos misterios, terminamos nuestro recorrido frente a este "libro siempre abierto" de la fe, donde la pasión y la gloria de los santos nos preparan para cruzar el umbral de salida con el alma llena de luz.',
  },
  {
    id: 'organo',
    type: 'sala',
    title: 'El Órgano Cavaillé-Coll: Una Joya Musical',
    subtitle: 'Doce toneladas de tubos franceses que llenan de música el bosque de piedra.',
    section: 'interior',
    image: '/organo.jpg',
    audio: '/organo.mp3',
    text: 'Doce toneladas de tubos franceses que llenan de música el bosque de piedra.',
    locucion: 'Si miramos hacia atrás, por encima de la entrada, vamos a ver esa mole de tubos que parece un edificio dentro de otro. Es el órgano Cavaillé-Coll, una pieza francesa que pesa toneladas y tiene casi.000 tubos de diferentes materiales. Fue diseñado especialmente para este volumen de aire tan gigante, así que cuando suena, la Basílica entera vibra. Es el cierre perfecto para los sentidos, una obra de ingeniería y arte que nos recuerda que la belleza también entra por los oídos.',
  },
  {
    id: 'salida',
    type: 'sala',
    title: 'Despedida: El Libro Siempre Abierto',
    subtitle: 'Regreso al mundo exterior llevando los secretos del bosque de piedra.',
    section: 'interior',
    image: '/salida.jpg',
    audio: '/salida_final.mp3',
    text: 'Regreso al mundo exterior llevando los secretos del bosque de piedra.',
    locucion: 'Estamos cruzando nuevamente el umbral del nártex para salir otra vez al mundo. Al dejar atrás el silencio del templo, nos llevamos con nosotros un viaje increíble: desde aquel primer milagro de Salvaire en la plaza y el abrazo de las tres portadas, hasta habernos internado en este bosque de piedra de la nave central. Hemos aprendido a leer la tabla de los pobres en los vitrales, recorrimos las naves de Uruguay y Paraguay con sus santos y confesionarios, y nos detuvimos en el corazón mismo del Altar Mayor. Rodeamos la corona de espinas del ábside, entramos en la intimidad del Camarín y conocimos mil historias. Pero fíjense bien, apenas hemos visto sus primeros secretos. Como bien dicen los que cuidan este lugar, la Basílica es un libro siempre abierto donde todos podemos volver a consultar y descubrir nuevos ejemplos de fe en cada rincón. Por eso, esta despedida es una invitación para volver a venir y seguir leyendo estas paredes de piedra rosada. Los esperamos, llenos de fe y entusiasmo... ¡hasta la próxima!',
  },
];

// Recorrido Vía Rápida: 15 paradas esenciales, en el orden del recorrido esencial.
// La referencia (Ref.) se calcula desde ALL_TOUR_STOPS para concordar con el título.
export const QUICK_TOUR_IDS: string[] = [
  'bienvenida',
  'neogotico',
  'portadas',
  'apostoles',
  'torres',
  'navecentral',
  'vitrales',
  'medalla',
  'crucero',
  'altar_mayor',
  'sentido_abside',
  'camarin_sacristia',
  'negro_manuel',
  'sagradocorazon',
  'salida',
];

export const TOUR_CATEGORIES: TourCategory[] = [
  { id: 'arquitectura', title: 'Arquitectura', description: 'Exterior, fachada, columnas, torres y estructura del templo.', image: '/portadas.jpg' },
  { id: 'interior', title: 'Interior', description: 'Nave central, crucero, altar mayor, camarín de la Virgen, capillas y altares.', image: '/navecentral.jpg' },
];
