// ============================================================
// AUDIOGUÍA COMPLEJO MUSEOGRÁFICO ENRIQUE UDAONDO
// Estructura de 66 paradas (0 a 65) con Museos y Salas
// ============================================================

export type MuseumId = 'historico' | 'transportes' | 'automovil' | 'otros';

export interface SalaTematica {
  id: string;
  title: string;
  stopIds: string[];
  /** Parada introductoria de la sala (la que da nombre/abre la sala). Se muestra en el renglón-título y NO se repite en el listado. */
  introStopId?: string;
}

export interface MuseumArea {
  id: MuseumId;
  title: string;
  shortTitle: string;
  description: string;
  image: string;
  introStopId: string;
  hasTour: boolean;
  salas: SalaTematica[];
}

export interface TourStop {
  id: string;
  stopNumber: number;
  title: string;
  subtitle: string;
  museum: MuseumId;
  salaId?: string;
  image: string;
  audio: string;
  text: string;
  locucion: string;
}

export const MUSEUM_AREAS: MuseumArea[] = [
  {
    id: 'historico',
    title: 'Museo Histórico y Colonial',
    shortTitle: 'Histórico',
    description: 'Cabildo de Luján, Casa del Virrey y el recorrido histórico desde los orígenes hasta la democracia.',
    image: '/museo-historico.jpg',
    introStopId: 'intro-historico',
    hasTour: true,
    salas: [
      {
        id: 'origenes-colonia',
        title: 'Orígenes y Colonia',
        stopIds: ['sala-virgen', 'promesa-salvaire', 'visitantes-ilustres', 'instrumentos-penalizacion'],
      },
      {
        id: 'pueblos-originarios',
        title: 'Pueblos Originarios y Encuentro',
        introStopId: 'pueblos-originarios',
        stopIds: [
          'pueblos-originarios',
          'encuentro-culturas',
          'pervivencia-color',
          'lienzo-cusco',
          'incunable-guarani',
          'monedas-potosi',
          'literatura-pedagogica',
        ],
      },
      {
        id: 'planta-alta-cabildo',
        title: 'Planta Alta y Cabildo de Luján',
        stopIds: ['sala-capitular', 'invasiones-inglesas', 'revolucion-mayo'],
      },
      {
        id: 'independencia',
        title: 'Independencia Continental',
        stopIds: [
          'sala-independencia',
          'frenar-enemigo-norte',
          'triunfo-libertad-continental',
          'aires-de-mar-brown',
          'oliendo-a-jazmin-mujer',
        ],
      },
      {
        id: 'autonomias-rosas',
        title: 'Autonomías Provinciales y Rosas',
        introStopId: 'autonomias-provinciales',
        stopIds: [
          'autonomias-provinciales',
          'giro-atlantico-frontera',
          'fusilamiento-dorrego',
          'liga-interior-caudillos',
          'generacion-37-exilio',
          'federacion-o-muerte',
          'sable-libertador',
        ],
      },
      {
        id: 'vida-gaucha',
        title: 'Vida Gaucha',
        introStopId: 'sala-vida-gaucha',
        stopIds: [
          'sala-vida-gaucha',
          'gaucho-centenario-1910',
          'tiempos-del-gaucho',
          'don-segundo-sombra',
          'cine-gauchesco',
          'plateria-rural-rastra',
        ],
      },
      {
        id: 'evolucion-contrastes',
        title: 'Evolución y Contrastes (1853-1983)',
        introStopId: 'evolucion-contrastes',
        stopIds: [
          'evolucion-contrastes',
          'guerra-unificacion',
          'argentina-moderna-riel',
          'siglo-xx-masas',
          'retorno-democratico-malvinas',
        ],
      },
    ],
  },
  {
      id: 'transportes',
      title: 'Museo de Transportes',
      shortTitle: 'Transportes',
      description: 'Evolución de los transportes: carretas, diligencias, La Porteña y grandes hazañas de la historia.',
      image: '/museo-transporte.webp',
      introStopId: 'intro-transportes',
      hasTour: true,
    salas: [
      {
        id: 'carretas-motores',
        title: 'Carretas y Motores (Del Pulso a Sangre al Vapor)',
        introStopId: 'carretas-motores',
        stopIds: [
          'carretas-motores',
          'litera-lopez-osornio',
          'carreta-ejercito-andes',
          'coche-sopandas-belgrano',
          'diligencias-iniciadores-pobladora',
          'locomotora-la-portena',
        ],
      },
      {
        id: 'grandes-hazanas',
        title: 'Grandes Hazañas (Aire, Mar y Tierra)',
        introStopId: 'hazanas-intrepidos',
        stopIds: [
          'hazanas-intrepidos',
          'plus-ultra',
          'gato-y-mancha',
          'velero-legh-vito-dumas',
          'carretilla-larregui',
          'sno-cat-venado-tuerto',
          'bicicleta-duomo-nunez',
        ],
      },
    ],
  },
  {
      id: 'automovil',
      title: 'Museo del Automóvil',
      shortTitle: 'Automóvil',
      description: 'Memoria en Movimiento: vehículos históricos, deportivos, presidenciales y el Papamóvil.',
      image: '/museo-automovil.jpg',
      introStopId: 'intro-automovil',
      hasTour: true,
    salas: [
      {
        id: 'memoria-movimiento',
        title: 'Memoria en Movimiento',
        introStopId: 'intro-automovil',
        stopIds: [
          'intro-automovil',
          'auto-buggy-1904',
          'packard-eight-1932',
          'ford-t-1921',
          'rambler-presidencial',
          'papamovil-linea-501',
          'blindado-banco-central',
        ],
      },
    ],
  },
  {
    id: 'otros',
    title: 'Otros Espacios y Monumentos',
    shortTitle: 'Otros Espacios',
    description: 'Patios, arquitectura doméstica colonial, campanas históricas y patrimonio al aire libre.',
    image: '/portadas.jpg',
    introStopId: 'intro-otros-espacios',
    hasTour: false,
    salas: [
      {
        id: 'espacios-monumentos',
        title: 'Patrimonio y Espacios Abiertos',
        stopIds: [
          'patio-del-aljibe',
          'campana-catedral-1810',
          'prensa-historica-tahona',
          'esculturas-jesuiticas',
          'casa-pepa-galarza',
        ],
      },
    ],
  },
];

export const ALL_TOUR_STOPS: TourStop[] = [
  // 0. Inicio General
  {
    id: 'bienvenida-general',
    stopNumber: 0,
    title: 'Bienvenida General (Plaza Belgrano)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    image: '/museo-historico.jpg',
    audio: '/bienvenida.mp3',
  },

  // 1. Museo Histórico - Intro
  {
    id: 'intro-historico',
    stopNumber: 1,
    title: 'Introducción al Museo Histórico y Colonial',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    image: '/paradas/historico.webp',
    audio: '/bienvenida.mp3',
  },

  // Orígenes y Colonia (2 a 5)
  {
    id: 'sala-virgen',
    stopNumber: 2,
    title: 'Sala de la Virgen',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'origenes-colonia',
    image: '/paradas/virgen.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'promesa-salvaire',
    stopNumber: 3,
    title: 'Promesa del Padre Salvaire en las Tolderías',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'origenes-colonia',
    image: '/paradas/salvaire.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'visitantes-ilustres',
    stopNumber: 4,
    title: 'Sala de Visitantes Ilustres y Prisioneros',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'origenes-colonia',
    image: '/paradas/ilustres.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'instrumentos-penalizacion',
    stopNumber: 5,
    title: 'Instrumentos de Penalización (Los Visitantes No Ilustres)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'origenes-colonia',
    image: '/paradas/penalizacion.webp',
    audio: '/bienvenida.mp3',
  },

  // Pueblos Originarios y Encuentro (6 a 12)
  {
    id: 'pueblos-originarios',
    stopNumber: 6,
    title: 'Sala de Pueblos Originarios',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'pueblos-originarios',
    image: '/paradas/originarios.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'encuentro-culturas',
    stopNumber: 7,
    title: 'Sala Encuentro de Culturas',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'pueblos-originarios',
    image: '/paradas/encuentro.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'pervivencia-color',
    stopNumber: 8,
    title: 'La Pervivencia del Color y la Sacralidad Andina',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'pueblos-originarios',
    image: '/paradas/pervivencia.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'lienzo-cusco',
    stopNumber: 9,
    title: 'El Lienzo de la Virgen en el Sitio de Cusco',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'pueblos-originarios',
    image: '/paradas/lienzo.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'incunable-guarani',
    stopNumber: 10,
    title: 'El Incunable Guaraní de 1705',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'pueblos-originarios',
    image: '/paradas/guarani.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'monedas-potosi',
    stopNumber: 11,
    title: 'Las Monedas de Potosí y el "Vale un Potosí"',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'pueblos-originarios',
    image: '/paradas/potosi.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'literatura-pedagogica',
    stopNumber: 12,
    title: 'La Literatura Pedagógica en Quechua y Aymara (1584)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'pueblos-originarios',
    image: '/paradas/quechua.webp',
    audio: '/bienvenida.mp3',
  },

  // Planta Alta y Cabildo (13 a 15)
  {
    id: 'sala-capitular',
    stopNumber: 13,
    title: 'La Sala Capitular y sus Atributos',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'planta-alta-cabildo',
    image: '/museo-historico.jpg',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'invasiones-inglesas',
    stopNumber: 14,
    title: 'Las Invasiones Inglesas y Luján',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'planta-alta-cabildo',
    image: '/museo-historico.jpg',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'revolucion-mayo',
    stopNumber: 15,
    title: 'Revolución de Mayo',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'planta-alta-cabildo',
    image: '/museo-historico.jpg',
    audio: '/bienvenida.mp3',
  },

  // Independencia Continental (16 a 20)
  {
    id: 'sala-independencia',
    stopNumber: 16,
    title: 'Sala de la Independencia',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'independencia',
    image: '/paradas/independencia.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'frenar-enemigo-norte',
    stopNumber: 17,
    title: 'La Necesidad de Frenar al Enemigo en el Norte',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'independencia',
    image: '/museo-historico.jpg',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'triunfo-libertad-continental',
    stopNumber: 18,
    title: 'Triunfo y Libertad en Escala Continental',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'independencia',
    image: '/museo-historico.jpg',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'aires-de-mar-brown',
    stopNumber: 19,
    title: 'Con Aires de Mar y Escuadra Patria (Alte. Brown)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'independencia',
    image: '/museo-historico.jpg',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'oliendo-a-jazmin-mujer',
    stopNumber: 20,
    title: 'Oliendo a Jazmín: La Mujer en la Gesta Patria',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'independencia',
    image: '/museo-historico.jpg',
    audio: '/bienvenida.mp3',
  },

  // Autonomías Provinciales y Rosas (21 a 27)
  {
    id: 'autonomias-provinciales',
    stopNumber: 21,
    title: 'Sala de Autonomías Provinciales',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'autonomias-rosas',
    image: '/paradas/autonomias.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'giro-atlantico-frontera',
    stopNumber: 22,
    title: 'El Giro Atlántico y la Frontera Ganadera',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'autonomias-rosas',
    image: '/paradas/atlantico.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'fusilamiento-dorrego',
    stopNumber: 23,
    title: 'El Fusilamiento de Dorrego y la Guerra Civil',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'autonomias-rosas',
    image: '/paradas/dorrego.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'liga-interior-caudillos',
    stopNumber: 24,
    title: 'La Liga del Interior y los Caudillos',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'autonomias-rosas',
    image: '/paradas/caudillos.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'generacion-37-exilio',
    stopNumber: 25,
    title: 'La Joven Generación del 37 y el Exilio',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'autonomias-rosas',
    image: '/paradas/exilio.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'federacion-o-muerte',
    stopNumber: 26,
    title: '"Federación o Muerte" y la Vida Cotidiana',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'autonomias-rosas',
    image: '/paradas/federacion.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'sable-libertador',
    stopNumber: 27,
    title: 'El Sable del Libertador',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'autonomias-rosas',
    image: '/museo-historico.jpg',
    audio: '/bienvenida.mp3',
  },

  // Vida Gaucha (28 a 33)
  {
    id: 'sala-vida-gaucha',
    stopNumber: 28,
    title: 'Sala de la Vida Gaucha',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'vida-gaucha',
    image: '/paradas/gaucha.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'gaucho-centenario-1910',
    stopNumber: 29,
    title: 'El Gaucho en el Centenario de 1910',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'vida-gaucha',
    image: '/paradas/gaucho.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'tiempos-del-gaucho',
    stopNumber: 30,
    title: 'Tiempos del Gaucho: Del Saladero al Frigorífico',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'vida-gaucha',
    image: '/paradas/saladero.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'don-segundo-sombra',
    stopNumber: 31,
    title: 'Don Segundo Sombra (El Escritorio de Ricardo Güiraldes)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'vida-gaucha',
    image: '/paradas/guiraldes.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'cine-gauchesco',
    stopNumber: 32,
    title: 'El Cine Gauchesco',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'vida-gaucha',
    image: '/paradas/cine.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'plateria-rural-rastra',
    stopNumber: 33,
    title: 'La Platería Rural de Argüello y la Rastra de Cuitiño',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'vida-gaucha',
    image: '/paradas/plateria.webp',
    audio: '/bienvenida.mp3',
  },

  // Evolución y Contrastes (34 a 38)
  {
    id: 'evolucion-contrastes',
    stopNumber: 34,
    title: 'Sala Evolución y Contrastes: 1853-1983',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'evolucion-contrastes',
    image: '/paradas/evolucion.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'guerra-unificacion',
    stopNumber: 35,
    title: 'Guerra y Unificación Nacional (Sala Intermedia A)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'evolucion-contrastes',
    image: '/paradas/guerra.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'argentina-moderna-riel',
    stopNumber: 36,
    title: 'La Argentina Moderna y el Riel (Sala Intermedia B)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'evolucion-contrastes',
    image: '/paradas/riel.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'siglo-xx-masas',
    stopNumber: 37,
    title: 'El Siglo XX de las Masas y Conflictos (Sala Intermedia C)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'evolucion-contrastes',
    image: '/paradas/masas.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'retorno-democratico-malvinas',
    stopNumber: 38,
    title: 'El Retorno Democrático (1983) y Malvinas (Sala Intermedia D)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'historico',
    salaId: 'evolucion-contrastes',
    image: '/paradas/malvinas.webp',
    audio: '/bienvenida.mp3',
  },

  // 2. Museo de Transportes - Intro
  {
    id: 'intro-transportes',
    stopNumber: 39,
    title: 'Introducción al Museo de Transportes',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'transportes',
    image: '/museo-transporte.webp',
    audio: '/bienvenida.mp3',
  },

  // Carretas y Motores (40 a 45)
  {
    id: 'carretas-motores',
    stopNumber: 40,
    title: 'Carretas y Motores: Del Pulso a Sangre al Vapor del Progreso',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'transportes',
    salaId: 'carretas-motores',
    image: '/museo-transporte.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'litera-lopez-osornio',
    stopNumber: 41,
    title: 'La Litera de Agustina López Osornio (ca. 1800)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'transportes',
    salaId: 'carretas-motores',
    image: '/museo-transporte.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'carreta-ejercito-andes',
    stopNumber: 42,
    title: 'La Carreta del Ejército de los Andes (ca. 1814)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'transportes',
    salaId: 'carretas-motores',
    image: '/museo-transporte.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'coche-sopandas-belgrano',
    stopNumber: 43,
    title: 'El Coche de Sopandas de Manuel Belgrano',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'transportes',
    salaId: 'carretas-motores',
    image: '/museo-transporte.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'diligencias-iniciadores-pobladora',
    stopNumber: 44,
    title: 'Diligencias "Iniciadores" y "La Pobladora"',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'transportes',
    salaId: 'carretas-motores',
    image: '/museo-transporte.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'locomotora-la-portena',
    stopNumber: 45,
    title: 'La Locomotora "La Porteña" (1857) y su Coche Original',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'transportes',
    salaId: 'carretas-motores',
    image: '/museo-transporte.webp',
    audio: '/bienvenida.mp3',
  },

  // Grandes Hazañas (46 a 52)
  {
    id: 'hazanas-intrepidos',
    stopNumber: 46,
    title: 'Hazañas: Intrépidos del Aire, el Mar y la Tierra',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'transportes',
    salaId: 'grandes-hazanas',
    image: '/museo-transporte.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'plus-ultra',
    stopNumber: 47,
    title: 'El Hidroavión "Plus Ultra" (1926)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'transportes',
    salaId: 'grandes-hazanas',
    image: '/museo-transporte.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'gato-y-mancha',
    stopNumber: 48,
    title: 'Los Caballos Criollos Gato y Mancha',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'transportes',
    salaId: 'grandes-hazanas',
    image: '/museo-transporte.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'velero-legh-vito-dumas',
    stopNumber: 49,
    title: 'El Velero "Legh" de Vito Dumas',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'transportes',
    salaId: 'grandes-hazanas',
    image: '/museo-transporte.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'carretilla-larregui',
    stopNumber: 50,
    title: 'La Carretilla de Guillermo Larregui',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'transportes',
    salaId: 'grandes-hazanas',
    image: '/museo-transporte.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'sno-cat-venado-tuerto',
    stopNumber: 51,
    title: 'Tractor de Nieve Sno-Cat "Venado Tuerto"',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'transportes',
    salaId: 'grandes-hazanas',
    image: '/museo-transporte.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'bicicleta-duomo-nunez',
    stopNumber: 52,
    title: 'La Bicicleta Duomo de Ricardo Núñez',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'transportes',
    salaId: 'grandes-hazanas',
    image: '/museo-transporte.webp',
    audio: '/bienvenida.mp3',
  },

  // 3. Museo del Automóvil - Intro
  {
    id: 'intro-automovil',
    stopNumber: 53,
    title: 'Museo del Automóvil: Memoria en Movimiento',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'automovil',
    image: '/museo-automovil.jpg',
    audio: '/bienvenida.mp3',
  },

  // Memoria en Movimiento (54 a 59)
  {
    id: 'auto-buggy-1904',
    stopNumber: 54,
    title: 'International Harvester Auto-Buggy (1904)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'automovil',
    salaId: 'memoria-movimiento',
    image: '/museo-automovil.jpg',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'packard-eight-1932',
    stopNumber: 55,
    title: 'Packard Standard Eight (1932)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'automovil',
    salaId: 'memoria-movimiento',
    image: '/museo-automovil.jpg',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'ford-t-1921',
    stopNumber: 56,
    title: 'Ford T (1921)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'automovil',
    salaId: 'memoria-movimiento',
    image: '/museo-automovil.jpg',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'rambler-presidencial',
    stopNumber: 57,
    title: 'Rambler Ambassador 380 Presidencial',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'automovil',
    salaId: 'memoria-movimiento',
    image: '/museo-automovil.jpg',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'papamovil-linea-501',
    stopNumber: 58,
    title: 'Papamóvil Colectivo Línea 501',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'automovil',
    salaId: 'memoria-movimiento',
    image: '/museo-automovil.jpg',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'blindado-banco-central',
    stopNumber: 59,
    title: 'Camión Blindado del Banco Central (1938)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'automovil',
    salaId: 'memoria-movimiento',
    image: '/museo-automovil.jpg',
    audio: '/bienvenida.mp3',
  },

  // 4. Otros Espacios y Monumentos (60 a 65)
  {
    id: 'intro-otros-espacios',
    stopNumber: 60,
    title: 'Otros Monumentos y Espacios del Complejo',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'otros',
    image: '/museo-historico.jpg',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'patio-del-aljibe',
    stopNumber: 61,
    title: 'Salida al Patio del Aljibe',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'otros',
    salaId: 'espacios-monumentos',
    image: '/paradas/aljibe.webp',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'campana-catedral-1810',
    stopNumber: 62,
    title: 'La Campana de la Catedral de Buenos Aires (1810)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'otros',
    salaId: 'espacios-monumentos',
    image: '/museo-historico.jpg',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'prensa-historica-tahona',
    stopNumber: 63,
    title: 'La Prensa Histórica o Tahona',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'otros',
    salaId: 'espacios-monumentos',
    image: '/museo-historico.jpg',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'esculturas-jesuiticas',
    stopNumber: 64,
    title: 'Las Esculturas Jesuíticas',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'otros',
    salaId: 'espacios-monumentos',
    image: '/museo-historico.jpg',
    audio: '/bienvenida.mp3',
  },
  {
    id: 'casa-pepa-galarza',
    stopNumber: 65,
    title: 'La Casa de Josefa "Pepa" Galarza (Fines del s. XVIII)',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    locucion: '',
    museum: 'otros',
    salaId: 'espacios-monumentos',
    image: '/museo-historico.jpg',
    audio: '/bienvenida.mp3',
  },
];


// Recorrido Vía Rápida (provisorio - a definir con el usuario)
export const QUICK_TOUR_IDS: string[] = [
  'bienvenida-general',
  'intro-historico',
  'sala-virgen',
  'pueblos-originarios',
  'sala-capitular',
  'revolucion-mayo',
  'sala-independencia',
  'sala-vida-gaucha',
  'intro-transportes',
  'locomotora-la-portena',
  'plus-ultra',
  'intro-automovil',
  'ford-t-1921',
  'casa-pepa-galarza',
];
